name: update-api-list

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
  schedule:
    - cron: '00 00 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - run: ls -al ${{ github.workspace }}
      - run: go run ${{ github.workspace }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
