name: update-api-list

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: go run ${{ github.workspace }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
